import React from "react";
import { Heading } from "@chakra-ui/layout";
import Head from "next/head";
import DesktopLayout from "../../layouts/DesktopLayout";
import BillingModule from "../../modules/Billing/BillingModule";

const DashboardPage = () => {
  return (
    <div>
      <Head>
        <title>Fondoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
            Paddle.Environment.set('sandbox');
            Paddle.Setup({ vendor: 3930 });
          `,
          }}
        ></script>
      </Head>
      <DesktopLayout>
        <Heading mb={6}>Billing</Heading>
        <BillingModule />
      </DesktopLayout>
    </div>
  );
};

export default DashboardPage;
