import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React, { useState } from "react";
import DesktopLayout from "../layouts/DesktopLayout";
import { SchedulesModule } from "../modules/Schedule/SchedulesModule";
import { CMSHome } from "../modules/CMS/Home";
import { Menu, MenuButton, MenuItem, MenuList } from "@chakra-ui/menu";
import { Button } from "@chakra-ui/button";
import { ChevronDownIcon } from "@chakra-ui/icons";
import { CMSAbout } from "../modules/CMS/About";

const CMSPage = () => {
  const initialValues = {
    home: true,
    about: false,
    deals: false,
    menu: false,
    reservation: false,
    reviews: false,
    gallery: false,
    contact: false,
  };

  // const [page, setPage] = useState(initialValues);

  const [page, setPage] = useState("Home");

  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>CMS</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <Box mb={6}>
              <Menu>
                {({ isOpen }) => (
                  <>
                    <MenuButton
                      colorScheme="gray"
                      bgColor="gray.800"
                      color="white"
                      _hover={{
                        background: "gray.900",
                      }}
                      _active={{
                        background: "gray.800",
                      }}
                      isActive={isOpen}
                      as={Button}
                      rightIcon={<ChevronDownIcon />}
                    >
                      {page}
                    </MenuButton>
                    <MenuList>
                      <MenuItem
                        onClick={() => {
                          setPage("Home");
                        }}
                      >
                        Home
                      </MenuItem>
                      <MenuItem
                        onClick={() => {
                          setPage("About");
                        }}
                      >
                        About
                      </MenuItem>
                      <MenuItem
                        onClick={() => {
                          setPage("Deals");
                        }}
                      >
                        Deals
                      </MenuItem>
                    </MenuList>
                  </>
                )}
              </Menu>
            </Box>
          </Box>
        </Grid>
        {page === "Home" ? <CMSHome /> : null}
        {page === "About" ? <CMSAbout /> : null}
        {page === "Deals" ? <CMSAbout /> : null}
      </DesktopLayout>
    </div>
  );
};

export default CMSPage;
