import React from "react";
import { Heading } from "@chakra-ui/layout";
import Head from "next/head";
import StatComponent from "../components/Stats/MainStat";
import TableComponent from "../components/Table/Table";
import { Skeleton } from "@chakra-ui/skeleton";
import { useGQLQuery } from "../shared-hooks/useGQLQuery";
import DesktopLayout from "../layouts/DesktopLayout";
import { useUserStore } from "../store/useUserStore";
import { GET_USER } from "../graphql/user";

const DashboardPage = () => {
  const userID = useUserStore((state) => state.userID);

  const { data, error, isLoading, isSuccess, isFetching } = useGQLQuery(
    "get-unique-user",
    GET_USER,
    {
      id: userID,
    }
  );

  const stats = [
    {
      label: "Total Orders",
      value: 10,
    },
  ];

  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Skeleton isLoaded={!isLoading}>
          <Heading mb={6}>Dashboard</Heading>
        </Skeleton>
        <Skeleton isLoaded={!isLoading}>
          <StatComponent data={stats} />
        </Skeleton>
        <Skeleton isLoaded={!isLoading}>
          <TableComponent />
        </Skeleton>
      </DesktopLayout>
    </div>
  );
};

export default DashboardPage;
