import { useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Grid, Heading, Stack, Text } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";

import DesktopLayout from "../layouts/DesktopLayout";

import FulfilmentModule from "../modules/Fulfilment/FulfilmentModule";
import AddDeliveryZone from "../modules/Fulfilment/AddDeliveryZone";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>Fulfilment</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <AddDeliveryZone />
          </Box>
        </Grid>
        <Box py={4}>
          <FulfilmentModule />
        </Box>
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
