import { useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Grid, Heading, Text } from "@chakra-ui/layout";
import Head from "next/head";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import StatComponent from "../components/Stats/MainStat";
import TableComponent from "../components/Table/Table";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid templateColumns="1fr 10fr">
        <NavBar />
        <Box bg={useColorModeValue("gray.50", "gray.800")}>
          <Header />
          <Box as="section" bg={useColorModeValue("gray.50", "gray.800")}>
            <Heading ml={6} mt={8}>
              Dashboard
            </Heading>
            <StatComponent />
            <TableComponent />
          </Box>
        </Box>
      </Grid>
    </div>
  );
}
