import { useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Grid, Heading, Stack, Text } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";

import DesktopLayout from "../layouts/DesktopLayout";

import FulfilmentModule from "../modules/Fulfilment/FulfilmentModule";
import AddDeliveryZone from "../modules/Fulfilment/AddDeliveryZone";
import OrdersModule from "../modules/Orders/OrdersModule";

const OrdersPage = () => {
  return (
    <div>
      <Head>
        <title>Fondoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>Orders</Heading>
        <Box py={4}>
          <OrdersModule />
        </Box>
      </DesktopLayout>
    </div>
  );
};

export default OrdersPage;
