import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import DesktopLayout from "../layouts/DesktopLayout";
import { AddUser } from "../modules/Users/AddUser";
import { SchedulesModule } from "../modules/Schedule/SchedulesModule";

const SchedulePage = () => {
  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>Schedules</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <AddUser />
          </Box>
        </Grid>
        <SchedulesModule />
      </DesktopLayout>
    </div>
  );
};

export default SchedulePage;
