import { Box, Grid, Heading, Stack, Text } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import { Tab, TabList, TabPanel, TabPanels, Tabs } from "@chakra-ui/react";

import DesktopLayout from "../layouts/DesktopLayout";
import { SettingsModule } from "../modules/Settings/SettingsModule";
import { BsFillInfoCircleFill } from "react-icons/bs";
import { RiEBike2Fill } from "react-icons/ri";
import { FaPalette } from "react-icons/fa";
import { AppearanceModule } from "../modules/Settings/AppearanceModule";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>Settings</Heading>
        <Tabs variant="soft-rounded" colorScheme={"blackAlpha"}>
          <TabList>
            <Tab>
              <Stack direction="row" alignItems="center">
                <Text>{<BsFillInfoCircleFill />}</Text> <Text>Information</Text>
              </Stack>
            </Tab>
            <Tab>
              <Stack direction="row" alignItems="center">
                <Text>{<FaPalette />}</Text> <Text>Appearance</Text>
              </Stack>
            </Tab>
          </TabList>
          <TabPanels>
            <TabPanel>
              <SettingsModule />
            </TabPanel>
            <TabPanel>
              <AppearanceModule />
            </TabPanel>
          </TabPanels>
        </Tabs>
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
