import Head from "next/head";

import { useRouter } from "next/router";

export default function CatchAll({ host, time, path }: any) {
  const router = useRouter();

  // Host available on query from router if blocking or fallback
  const query = router.query;

  // Or params
  console.log(host, time, query);

  return (
    <div>
      <Head>
        <title>Next Multi Host Slug Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Catch All - Host: <i>{host}</i>
      </h1>
      <p>
        Path: <i>/{path}</i> {" - "}
        Generated At: <i>{time}</i>
      </p>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  console.log(context);

  const time = Date.now();
  const host = context.req.headers.host.split(":")[0]; // Remove port to be consistant with rewrites

  return {
    props: {
      host,
      path: (context.params.path || []).join("/"),
      time,
    },
  };
}
