import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import DesktopLayout from "../../layouts/DesktopLayout";
import { AddCoupon } from "../../modules/Promotions/Coupons/AddCoupon";
import { CouponsModule } from "../../modules/Promotions/Coupons/CouponsModule";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>Fondoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DesktopLayout>
        <Heading mb={10}>Coupons</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <AddCoupon />
          </Box>
        </Grid>
        <CouponsModule />
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
