import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import DesktopLayout from "../../layouts/DesktopLayout";
import { AddOffer } from "../../modules/Promotions/Offers/AddOffer";
import { OffersModule } from "../../modules/Promotions/Offers/OffersModule";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DesktopLayout>
        <Heading mb={10}>Offers</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <AddOffer />
          </Box>
        </Grid>
        <OffersModule />
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
