import React from "react";
import { Heading } from "@chakra-ui/layout";
import Head from "next/head";
import StatComponent from "../../components/Stats/MainStat";
import TableComponent from "../../components/Table/Table";
import { Skeleton } from "@chakra-ui/skeleton";
import { useGQLQuery } from "../../shared-hooks/useGQLQuery";
import DesktopLayout from "../../layouts/DesktopLayout";
import { useUserStore } from "../../store/useUserStore";
import { useRouter } from "next/router";
import { GET_ALL_RESTAURANTS_STAT } from "../../graphql/admin/restaurant";
import { GET_ALL_USERS_STAT } from "../../graphql/admin/user";
import { GET_ALL_ORDERS_STAT } from "../../graphql/admin/order";

const DashboardPage = () => {
  const role = useUserStore((state) => state.role);

  const router = useRouter();

  const restaurantQuery = useGQLQuery(
    "get-all-restaurants-stat",
    GET_ALL_RESTAURANTS_STAT
  );

  const userQuery = useGQLQuery("get-all-users-stat", GET_ALL_USERS_STAT);

  const orderQuery = useGQLQuery("get-all-orders-stat", GET_ALL_ORDERS_STAT);

  const data = [
    {
      label: "Total Restaurants",
      value: restaurantQuery.data
        ? restaurantQuery.data.restaurants.length
        : "",
    },
    {
      label: "Total Users",
      value: userQuery.data ? userQuery.data.users.length : "",
    },
    {
      label: "Total Orders",
      value: orderQuery.data ? orderQuery.data.orders.length : "",
    },
  ];

  React.useEffect(() => {
    if (role !== "Admin") {
      router.push("/dashboard");
    }
  });

  return (
    <div>
      <Head>
        <title>Fondoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Skeleton isLoaded={!restaurantQuery.isLoading}>
          <Heading mb={6}>Hi </Heading>
        </Skeleton>
        <Skeleton isLoaded={!restaurantQuery.isLoading}>
          <StatComponent data={data} />
        </Skeleton>
        <Skeleton isLoaded={!restaurantQuery.isLoading}>
          <TableComponent />
        </Skeleton>
      </DesktopLayout>
    </div>
  );
};

export default DashboardPage;
