import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import DesktopLayout from "../../layouts/DesktopLayout";
import { AddRestaurant } from "../../modules/Admin/Restaurants/AddRestaurant";
import { RestaurantsAdminModule } from "../../modules/Admin/Restaurants/RestaurantsAdminModule";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>Fondoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DesktopLayout>
        <Heading mb={10}>Restaurants</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <AddRestaurant />
          </Box>
        </Grid>
        <RestaurantsAdminModule />
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
