import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import DesktopLayout from "../../layouts/DesktopLayout";
import { AdminAddUser } from "../../modules/Admin/Users/AddUser";
import { AdminUsersModule } from "../../modules/Admin/Users/UsersModule";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>Fondoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>Users</Heading>
        <Grid templateColumns="1fr 1fr">
          <Box />
          <Box mr={8} gridArea="right">
            <AdminAddUser />
          </Box>
        </Grid>
        <AdminUsersModule />
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
