import { GraphQLClient } from "graphql-request";
import Head from "next/head";
import { Constants } from "../../config";
import { GET_RESTAURANT_INFO } from "../../graphql/restaurant";
import HeroContainer from "../../components/hero/HeroContainer";
import DefaultLayout from "../../layouts/DefaultLayout";
import { getPlaiceholder } from "plaiceholder";
import TezzBitesGA from "../../components/analytics/TezzBitesGA";
import PopularDishesContainer from "../../modules/home/PopularDishesContainer";
import { AboutContainer } from "../../modules/home/AboutContainer";
import ReservationContainer from "../../modules/home/ReservationContainer";
import { Stack } from "@chakra-ui/layout";

export default function Home({ host, rdata, cdata, imageProps }: any) {
  console.log(rdata);

  return (
    <>
      <Head>
        <title>{rdata ? rdata.name : "TezzBites Partner Website"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TezzBitesGA />
      {rdata && cdata ? (
        <DefaultLayout rdata={rdata} cdata={cdata}>
          <Stack>
            <HeroContainer
              imageProps={imageProps}
              rdata={rdata}
              cdata={cdata}
            />
            <AboutContainer />
            <PopularDishesContainer rdata={rdata} cdata={cdata} />
            <ReservationContainer rdata={rdata} cdata={cdata} />
          </Stack>
        </DefaultLayout>
      ) : (
        <div>Site data not found</div>
      )}
    </>
  );
}

export async function getStaticProps(context: any) {
  const host = context.params.host;

  const endpoint = Constants.GraphQL_API;

  const graphQLClient = new GraphQLClient(endpoint);

  const fetchData = await graphQLClient.request(GET_RESTAURANT_INFO, {
    domain: host,
  });

  const rdata = fetchData.restaurantConfig.restaurant
    ? fetchData.restaurantConfig.restaurant
    : null;

  const cdata = fetchData.restaurantConfig ? fetchData.restaurantConfig : null;

  const { base64, img } = await getPlaiceholder(
    rdata.coverImage ? Constants.CDN + rdata.coverImage : ""
  );
  console.log(img);

  return {
    props: {
      host,
      rdata,
      cdata,
      imageProps: {
        ...img,
        blurDataURL: base64,
      },
    },
    revalidate: 30,
  };
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: "blocking",
  };
}
