import { useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import Header from "../../components/Header/Header";
import NavBar from "../../components/NavBar";

import { SettingsModule } from "../../modules/Settings/SettingsModule";

const SettingsPage = () => {
  return (
    <div>
      <div>
        <Head>
          <title>TezzBites</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Grid templateColumns="1fr 10fr">
          <NavBar />
          <Box bg={useColorModeValue("gray.50", "gray.800")}>
            <Header />
            <Box as="section" bg={useColorModeValue("gray.50", "gray.800")}>
              <Heading ml={6} mt={8}>
                Settings
              </Heading>
              <SettingsModule />
            </Box>
          </Box>
        </Grid>
      </div>
    </div>
  );
};

export default SettingsPage;
