import { useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Grid, Heading } from "@chakra-ui/layout";
import Head from "next/head";
import React from "react";
import Header from "../../components/Header/Header";
import NavBar from "../../components/NavBar";
import DesktopLayout from "../../layouts/DesktopLayout";

import { SettingsModule } from "../../modules/Settings/SettingsModule";

const SettingsPage = () => {
  return (
    <div>
      <Head>
        <title>TezzBites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopLayout>
        <Heading mb={10}>Settings</Heading>
        <SettingsModule />
      </DesktopLayout>
    </div>
  );
};

export default SettingsPage;
