# name: api:deploy
# on:
#   push:
#     paths:
#       - "api/dist/**"
#     branches:
#       - main

# jobs:
#   build:
#     name: deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           password: ${{ secrets.EC2_PASSWORD }}
#           script: cd tezzbites && git pull origin main && prisma migrate deploy && pm2 restart all
