name: Deploy to Heroku (API)

on:
  push:
    branches:
      - prod
    paths:
      - "api/**"
      - ".github/workflows/api.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add API remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy API to Heroku
        run: git push heroku `git subtree split --prefix api main`:refs/heads/prod --force
