import Head from "next/head";

export default function Home({ host, time, path }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Order Page</h1>
      <h2>Host: {host}</h2>
    </>
  );
}

export async function getStaticProps(context: any) {
  console.log("getStaticProps", context);

  const host = context.params.host;

  const time = Date.now();

  return {
    props: {
      host,
      time,
    },
    // revalidate: 10,
  };
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: "blocking",
  };
}
